### ISSUE TITLE
提示posframe没安装

### ISSUE THREAD

**Issue by BH1SCW** [eggcaker/.doom.d#1]
我clone了你的配置，把extensions和module拷贝过来
init.el 中加入private 那两行
doom sync一下 
启动emacs 切换到中文，输入后提示posframe未安装

请教一下以上步骤是正常的吗？

**Comment by eggcaker** [comment]
看看.emacs.d里postframe有没有安装？墙？

**Comment by BH1SCW** [comment]
装了， 我这没墙 没事，我再试试 正好换了个环境
